shopquanao/shopquanao/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shopquanao.Models;
using PagedList;
namespace shopquanao.Controllers
{
    public class AdminController : BaseController
    {
        MyDataDataContext data = new MyDataDataContext();

        #region

        public ActionResult Index()
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();
            ViewBag.Online = HttpContext.Application["Online"].ToString();

            ViewBag.TongDoanhThu = ThongKeDoanhThu();
            ViewBag.TongDDH = ThongKeDonHang();
            ViewBag.TongKhachHang = ThongKeKhachHang();

            return View();
        }

        public decimal ThongKeDoanhThu()
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Sum(
                n => n.soluong * n.gia
            ).Value;
            return TongDoanhThu;
        }

        public double ThongKeDonHang()
        {
            double slddh = data.DonHangs.Count();
            return slddh;
        }
        public double ThongKeKhachHang()
        {
            double slkh = data.KhachHangs.Count();
            return slkh;
        }
        public ActionResult DoanhThu()
        {
            ViewBag.TongDoanhThu = ThongKeDoanhThu();

            var getlist = data.SanPhams.ToList();
            SelectList list = new SelectList(getlist, "masp", "tensp");

            return View();
        }
        public ActionResult DoanhThuNgay(FormCollection collection)
        {
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            var getDay = DateTime.Parse(ngaygiao.ToString()).Day;
            var getMonth = DateTime.Parse(ngaygiao.ToString()).Month;
            var getYear = DateTime.Parse(ngaygiao.ToString()).Year;

            ViewBag.Ngay = getDay;
            ViewBag.Thang = getMonth;
            ViewBag.Nam = getYear;
            ViewBag.DoanhThuNgay = ThongKeDoanhThuNgay(getDay, getMonth, getYear);
            ViewBag.DoanhThuNgayCount = ThongKeDoanhThuNgayCount(getDay, getMonth, getYear);
            List<DonHang> donhang = data.DonHangs.ToList();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            var ViewSP = (from sp in donhang
                          join ct in ctdh
                          on sp.madon equals ct.madon
                          where sp.ngaydat.Value.Day == getDay && sp.ngaydat.Value.Month == getMonth && sp.ngaydat.Value.Year == getYear && ct.status == 1
                          select new ViewModel
                          {
                              donhang = sp,
                              ctdh = ct
                          }).GroupBy(test => test.ctdh.madon)
                   .Select(grp => grp.First());


            ViewBag.ListCountDTN = ViewSP;

            return View();
        }
        public ActionResult DoanhThuThang(FormCollection collection)
        {
            var ngaygiao = String.Format("{0:mm/dd/yyyy}", collection["NgayGiao"]);
            var getMonth = DateTime.Parse(ngaygiao.ToString()).Month;
            var getYear = DateTime.Parse(ngaygiao.ToString()).Year;

            ViewBag.Thang = getMonth;
            ViewBag.Nam = getYear;
            ViewBag.DoanhThuThang = ThongKeDoanhThuThang(getMonth, getYear);
            ViewBag.DoanhThuThangCount = ThongKeDoanhThuThangCount(getMonth, getYear);

            List<DonHang> donhang = data.DonHangs.ToList();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            var ViewSP = (from sp in donhang
                          join ct in ctdh
                          on sp.madon equals ct.madon
                          where sp.ngaydat.Value.Month == getMonth && sp.ngaydat.Value.Year == getYear && ct.status == 1
                          select new ViewModel
                          {
                              donhang = sp,
                              ctdh = ct
                          }).GroupBy(test => test.ctdh.madon)
                   .Select(grp => grp.First());


            ViewBag.ListCountDTN = ViewSP;

            return View();
        }
        public decimal ThongKeDoanhTungSanPhamChoGia(int id)
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Where(m => m.masp == id && m.status == 1)
                .Sum(
                n => (n.soluong * n.gia)
            ).Value;
            return TongDoanhThu;
        }
        public decimal ThongKeDoanhTungSanPhamChoSL(int id)
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Where(m => m.masp == id && m.status == 1)
                .Sum(
                n => (n.soluong)
            ).Value;
            return TongDoanhThu;
        }
        public decimal ThongKeDoanhThuNgay(int Ngay, int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Day == Ngay && n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong * n.gia).Value.ToString()
                );
            }
            return tongtien;
        }
        public decimal ThongKeDoanhThuNgayCount(int Ngay, int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Day == Ngay && n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong).Value.ToString()
                );
            }
            return tongtien;
        }
        public decimal ThongKeDoanhThuThang(int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong * n.gia).Value.ToString()
                );
            }
            return tongtien;
        }
        public decimal ThongKeDoanhThuThangCount(int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong).Value.ToString()
                );
            }
            return tongtien;
        }

        public ActionResult QLSanPham(int? page)
        {
            if (page == null) page = 1;
            var all_sach = (from s in data.SanPhams select s).OrderBy(m => m.masp);
            int pageSize = 5;
            int pageNum = page ?? 1;
            return View(all_sach.ToPagedList(pageNum, pageSize));
        }


        public ActionResult Details(int id)
        {
            var D_SanPham = data.SanPhams.Where(m => m.masp == id).First();
            return View(D_SanPham);
        }

        public ActionResult Create()
        {
            var getlist = data.DanhMucs.ToList();
            SelectList list = new SelectList(getlist, "idDanhmuc", "tendanhmuc");
            ViewBag.fulllist = list;

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection collection, SanPham s)
        {
            var E_tensp = collection["tensp"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_giamgia = Convert.ToInt32(collection["giamgia"]);
            var E_ngaycapnhat = DateTime.Now;
            var E_iddanhmuc = collection["idDanhmuc"];
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            var E_mota = collection["mota"];
            if (string.IsNullOrEmpty(E_tensp))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tensp = E_tensp.ToString();
                s.hinh = E_hinh;
                s.giaban = E_giaban;
                s.giamgia = E_giamgia;

                s.idDanhmuc = Convert.ToInt32(E_iddanhmuc);
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                s.mota = E_mota;

                var x = s.giaban;
                var y = s.giamgia;

                var z = (x * y) / 100;

                var price = x - z;

                s.giakhuyenmai = price;

                data.SanPhams.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        public ActionResult Edit(int id)
        {
            var getlist = data.DanhMucs.ToList();
            SelectList list = new SelectList(getlist, "idDanhmuc", "tendanhmuc");
            ViewBag.fulllist = list;

            var E_sach = data.SanPhams.First(m => m.masp == id);
            return View(E_sach);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sach = data.SanPhams.First(m => m.masp == id);
            var E_tensach = collection["tensp"];
            var E_hinh = collection["hinh"];

shopquanao/shopquanao/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shopquanao.Models;

namespace shopquanao.Controllers
{
    public class DanhMucController : BaseController
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: DanhMuc
        //---------Index-DanhMuc------------
        public ActionResult Index()
        {
            var all_danhmuc = from tt in data.DanhMucs select tt;
            return View(all_danhmuc);
        }

        //---------Detail-DanhMuc------------
        public ActionResult Details(int id)
        {
            var Data_danhmuc = data.DanhMucs.Where(m => m.idDanhmuc == id).First();
            return View(Data_danhmuc);
        }

        //---------Create(tao moi the loai sach)-DanhMuc------------
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, DanhMuc tl)
        {
            var ten = collection["tendanhmuc"];
            if (string.IsNullOrEmpty(ten))
            {
                ViewData["Error"] = "Du lieu khong duoc de trong!";
            }
            else
            {
                tl.tendanhmuc = ten;
                data.DanhMucs.InsertOnSubmit(tl);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        //---------Edit-DanhMuc------------
        public ActionResult Edit(int id)
        {
            var E_category = data.DanhMucs.First(m => m.idDanhmuc == id);
            return View(E_category);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var danhmuc = data.DanhMucs.First(m => m.idDanhmuc == id);
            var E_tendanhmuc = collection["tendanhmuc"];
            danhmuc.idDanhmuc = id;
            if (string.IsNullOrEmpty(E_tendanhmuc))
            {
                ViewData["Error"] = "Du lieu khong duoc de trong!";
            }
            else
            {
                danhmuc.tendanhmuc = E_tendanhmuc;
                UpdateModel(danhmuc);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }

        //---------Delete------------
        public ActionResult Delete(int id)
        {
            var D_danhmuc = data.DanhMucs.First(m => m.idDanhmuc == id);
            return View(D_danhmuc);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_danhmuc = data.DanhMucs.Where(m => m.idDanhmuc == id).First();
            data.DanhMucs.DeleteOnSubmit(D_danhmuc);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }

    }
}

shopquanao/shopquanao/Views/DanhMuc/Create.cshtml
@model shopquanao.Models.DanhMuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="menu_option-head2">Thêm danh mục</div>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.tendanhmuc, htmlAttributes: new { @class = "col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tendanhmuc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tendanhmuc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

shopquanao/shopquanao/Views/DanhMuc/Delete.cshtml
@model shopquanao.Models.DanhMuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12">

    <dl class="dl-horizontal">
        <div class="menu_option-head2">Xóa danh mục</div>
        <hr />
        <div>
            <strong>@Html.DisplayNameFor(model => model.tendanhmuc)</strong>
        </div>

        <div>
            @Html.DisplayFor(model => model.tendanhmuc)
        </div>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

shopquanao/shopquanao/Views/DanhMuc/Details.cshtml
@model shopquanao.Models.DanhMuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12">

    <dl class="dl-horizontal">
        <div class="menu_option-head2">Chi tiết</div>
        <hr />
        <div>
            <strong>Tên danh mục</strong>
        </div>

        <div>
            @Html.DisplayFor(model => model.tendanhmuc)
        </div>

    </dl>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.idDanhmuc }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

shopquanao/shopquanao/Views/DanhMuc/Edit.cshtml
@model shopquanao.Models.DanhMuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="menu_option-head2">Sửa sản phẩm</div>
            <hr />
            <table class="table">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.idDanhmuc)

                <div class="form-group">
                    @Html.LabelFor(model => model.tendanhmuc, htmlAttributes: new { @class = "col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.tendanhmuc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.tendanhmuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </table>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

shopquanao/shopquanao/Views/DanhMuc/Index.cshtml
@model IEnumerable<shopquanao.Models.DanhMuc>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12">
    <table class="table">
        <div class="menu_option-head">Danh Mục Sản Phẩm</div>
        <div class="add-product">
            <a href="@Url.Action("Create")">Thêm danh mục</a>
        </div>

        <thead>
        <th>Tên Danh Muc</th>
        <th>
            Chức năng
        </th>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.tendanhmuc)
                </td>
                <td>
                    <a href="@Url.Action("Details", "DanhMuc", new { id = item.idDanhmuc })" class="btn btn-success"><i class="fa-solid fa-eye"></i></a>
                    <a href="@Url.Action("Edit", "DanhMuc", new { id = item.idDanhmuc })" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                    <a href="@Url.Action("Delete", "DanhMuc", new { id = item.idDanhmuc })" class="btn btn-danger"><i class="fa-solid fa-trash-can"></i></a>
                </td>
            </tr>
        }

    </table>
    <div>
        @Html.ActionLink("Back to List", "Index", "Admin")
    </div>

</div>

<style>
    .MenuTrang li {
        display: inline;
    }
</style>
<style type="text/css">
    #mau-nut a {
        clear: both;
        background-color: orange;
        color: snow;
    }

        #mau-nut a:hover {
            background-color: darkcyan;
            color: snow;
        }
</style>