shopquanao/shopquanao/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shopquanao.Models;
using PagedList;
namespace shopquanao.Controllers
{
    public class AdminController : BaseController
    {
        MyDataDataContext data = new MyDataDataContext();

        #region

        public ActionResult Index()
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();
            ViewBag.Online = HttpContext.Application["Online"].ToString();

            ViewBag.TongDoanhThu = ThongKeDoanhThu();
            ViewBag.TongDDH = ThongKeDonHang();
            ViewBag.TongKhachHang = ThongKeKhachHang();

            return View();
        }

        public decimal ThongKeDoanhThu()
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Sum(
                n => n.soluong * n.gia
            ).Value;
            return TongDoanhThu;
        }

        public double ThongKeDonHang()
        {
            double slddh = data.DonHangs.Count();
            return slddh;
        }
        public double ThongKeKhachHang()
        {
            double slkh = data.KhachHangs.Count();
            return slkh;
        }
        public ActionResult DoanhThu()
        {
            ViewBag.TongDoanhThu = ThongKeDoanhThu();

            var getlist = data.SanPhams.ToList();
            SelectList list = new SelectList(getlist, "masp", "tensp");

            return View();
        }
        public ActionResult DoanhThuNgay(FormCollection collection)
        {
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            var getDay = DateTime.Parse(ngaygiao.ToString()).Day;
            var getMonth = DateTime.Parse(ngaygiao.ToString()).Month;
            var getYear = DateTime.Parse(ngaygiao.ToString()).Year;

            ViewBag.Ngay = getDay;
            ViewBag.Thang = getMonth;
            ViewBag.Nam = getYear;
            ViewBag.DoanhThuNgay = ThongKeDoanhThuNgay(getDay, getMonth, getYear);
            ViewBag.DoanhThuNgayCount = ThongKeDoanhThuNgayCount(getDay, getMonth, getYear);
            List<DonHang> donhang = data.DonHangs.ToList();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            var ViewSP = (from sp in donhang
                          join ct in ctdh
                          on sp.madon equals ct.madon
                          where sp.ngaydat.Value.Day == getDay && sp.ngaydat.Value.Month == getMonth && sp.ngaydat.Value.Year == getYear && ct.status == 1
                          select new ViewModel
                          {
                              donhang = sp,
                              ctdh = ct
                          }).GroupBy(test => test.ctdh.madon)
                   .Select(grp => grp.First());


            ViewBag.ListCountDTN = ViewSP;

            return View();
        }
        public ActionResult DoanhThuThang(FormCollection collection)
        {
            var ngaygiao = String.Format("{0:mm/dd/yyyy}", collection["NgayGiao"]);
            var getMonth = DateTime.Parse(ngaygiao.ToString()).Month;
            var getYear = DateTime.Parse(ngaygiao.ToString()).Year;

            ViewBag.Thang = getMonth;
            ViewBag.Nam = getYear;
            ViewBag.DoanhThuThang = ThongKeDoanhThuThang(getMonth, getYear);
            ViewBag.DoanhThuThangCount = ThongKeDoanhThuThangCount(getMonth, getYear);

            List<DonHang> donhang = data.DonHangs.ToList();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            var ViewSP = (from sp in donhang
                          join ct in ctdh
                          on sp.madon equals ct.madon
                          where sp.ngaydat.Value.Month == getMonth && sp.ngaydat.Value.Year == getYear && ct.status == 1
                          select new ViewModel
                          {
                              donhang = sp,
                              ctdh = ct
                          }).GroupBy(test => test.ctdh.madon)
                   .Select(grp => grp.First());


            ViewBag.ListCountDTN = ViewSP;

            return View();
        }
        public decimal ThongKeDoanhTungSanPhamChoGia(int id)
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Where(m => m.masp == id && m.status == 1)
                .Sum(
                n => (n.soluong * n.gia)
            ).Value;
            return TongDoanhThu;
        }
        public decimal ThongKeDoanhTungSanPhamChoSL(int id)
        {
            decimal TongDoanhThu = data.ChiTietDonHangs
                .Where(m => m.masp == id && m.status == 1)
                .Sum(
                n => (n.soluong)
            ).Value;
            return TongDoanhThu;
        }
        public decimal ThongKeDoanhThuNgay(int Ngay, int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Day == Ngay && n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong * n.gia).Value.ToString()
                );
            }
            return tongtien;
        }
        public decimal ThongKeDoanhThuNgayCount(int Ngay, int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Day == Ngay && n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong).Value.ToString()
                );
            }
            return tongtien;
        }
        public decimal ThongKeDoanhThuThang(int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong * n.gia).Value.ToString()
                );
            }
            return tongtien;
        }
        public decimal ThongKeDoanhThuThangCount(int Thang, int Nam)
        {
            var listDDH = data.DonHangs.Where(n => n.ngaydat.Value.Month == Thang &&
            n.ngaydat.Value.Year == Nam);
            decimal tongtien = 0;
            foreach (var item in listDDH)
            {
                tongtien += decimal.Parse(item.ChiTietDonHangs
                    .Where(m => m.status == 1)
                    .Sum(
                    n => n.soluong).Value.ToString()
                );
            }
            return tongtien;
        }

        public ActionResult QLSanPham(int? page)
        {
            if (page == null) page = 1;
            var all_sach = (from s in data.SanPhams select s).OrderBy(m => m.masp);
            int pageSize = 5;
            int pageNum = page ?? 1;
            return View(all_sach.ToPagedList(pageNum, pageSize));
        }


        public ActionResult Details(int id)
        {
            var D_SanPham = data.SanPhams.Where(m => m.masp == id).First();
            return View(D_SanPham);
        }

        public ActionResult Create()
        {
            var getlist = data.DanhMucs.ToList();
            SelectList list = new SelectList(getlist, "idDanhmuc", "tendanhmuc");
            ViewBag.fulllist = list;

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection collection, SanPham s)
        {
            var E_tensp = collection["tensp"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_giamgia = Convert.ToInt32(collection["giamgia"]);
            var E_ngaycapnhat = DateTime.Now;
            var E_iddanhmuc = collection["idDanhmuc"];
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            var E_mota = collection["mota"];
            if (string.IsNullOrEmpty(E_tensp))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tensp = E_tensp.ToString();
                s.hinh = E_hinh;
                s.giaban = E_giaban;
                s.giamgia = E_giamgia;

                s.idDanhmuc = Convert.ToInt32(E_iddanhmuc);
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                s.mota = E_mota;

                var x = s.giaban;
                var y = s.giamgia;

                var z = (x * y) / 100;

                var price = x - z;

                s.giakhuyenmai = price;

                data.SanPhams.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        public ActionResult Edit(int id)
        {
            var getlist = data.DanhMucs.ToList();
            SelectList list = new SelectList(getlist, "idDanhmuc", "tendanhmuc");
            ViewBag.fulllist = list;

            var E_sach = data.SanPhams.First(m => m.masp == id);
            return View(E_sach);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sach = data.SanPhams.First(m => m.masp == id);
            var E_tensach = collection["tensp"];
            var E_hinh = collection["hinh"];

shopquanao/shopquanao/Controllers/QLDonHangController.cs
using shopquanao.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace shopquanao.Controllers
{
    public class QLDonHangController : BaseController
    {
        MyDataDataContext data = new MyDataDataContext();

        //---------Index-DanhMuc------------
        public ActionResult Index()
        {
            var all_danhmuc = from tt in data.DonHangs select tt;
            return View(all_danhmuc);

        }

        //---------Detail-------------
        public ActionResult DetailsCTDH(int id)
        {
            var results = (from t1 in data.ChiTietDonHangs
                          join t2 in data.DonHangs
                          on new { t1.madon} equals
                              new { t2.madon }
                          where t2.madon == id 
                          select t1).ToList();

            List<KhachHang> khachhang = data.KhachHangs.ToList();
            List<DonHang> donhang = data.DonHangs.ToList();

            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            List<SanPham> sanpham = data.SanPhams.ToList();

            var ViewKH = from kh in khachhang join dh in donhang
                         on kh.makh equals dh.makh
                         where dh.madon == id && kh.makh == dh.makh
                         select new ViewModel
                         {
                             khachhang = kh,
                             donhang = dh
                         };

            var ViewSP = from sp in sanpham join ct in ctdh
                         on sp.masp equals ct.masp
                         where ct.madon == id && sp.masp == ct.masp
                         select new ViewModel
                         {
                             sanpham = sp,
                             ctdh = ct
                         };

            ViewBag.ViewChiTietDH = ViewKH;
            ViewBag.ViewSP = ViewSP;

            return View(results);
        }

        //---------Edit-Don Hang------------
        public ActionResult Edit(int id)
        {
            var E_category = data.DonHangs.First(m => m.madon == id);
            return View(E_category);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var danhmuc = data.DonHangs.First(m => m.madon == id);
            var E_tendanhmuc = collection["giaohang"];
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            danhmuc.madon = id;
            if (string.IsNullOrEmpty(E_tendanhmuc))
            {
                ViewData["Error"] = "Du lieu khong duoc de trong!";
            }
            else
            {
                danhmuc.giaohang = E_tendanhmuc;
                danhmuc.ngaygiao = DateTime.Parse(ngaygiao);
                UpdateModel(danhmuc);
                
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }

        //---------Delete------------
        public ActionResult Delete(int id)
        {
            var D_danhmuc = data.DonHangs.FirstOrDefault(n => n.madon == id);
            return View(D_danhmuc);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {

            var D_danhmuc2 = data.ChiTietDonHangs.Where(m => m.madon == id).First();
            data.ChiTietDonHangs.DeleteOnSubmit(D_danhmuc2);
            data.SubmitChanges();

            var D_danhmuc = data.DonHangs.Where(m => m.madon == id).First();
            data.DonHangs.DeleteOnSubmit(D_danhmuc);
            data.SubmitChanges();

            return RedirectToAction("Index");
        }

    }
}

shopquanao/shopquanao/Views/Admin/ChiaQuyen.cshtml
@{
    ViewBag.Title = "ChiaQuyen";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@if (Session["Staff"] != null)
{
    <div class="p-3 text-danger">Bạn không có quyền truy cập trang web này!!!</div>
}
else
{
<div class="col-12">
    <h3 class="p-2">Quản lý phân quyền</h3>

    <table class="table">
        <tr>
            <th>
                Họ tên
            </th>
            <th>
                Email
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Sđt
            </th>
            <th>
                Ngày sinh
            </th>
            <th>
                Quyền
            </th>
            <th></th>
        </tr>

        @foreach (var m in ViewBag.Main)
        {
            <tr>
                <td>
                    @m.khachhang.hoten
                </td>
                <td>
                    @m.khachhang.email
                </td>
                <td>
                    @m.khachhang.diachi
                </td>
                <td>
                    @m.khachhang.dienthoai
                </td>
                <td>
                    @m.khachhang.ngaysinh
                </td>
                <td>
                    @m.khachhangrole.RoleName
                </td>
                <td>
                    @Html.ActionLink("Edit", "SuaQuyen", new { id = @m.khachhang.makh })
                </td>
            </tr>
        }

    </table>

</div>
}

shopquanao/shopquanao/Views/Admin/Delete.cshtml
@model shopquanao.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="col-lg-12 padding-8">

    <dl class="dl-horizontal" style="overflow: hidden;">
        <div class="menu_option-head2">Xóa sản phẩm</div>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.idDanhmuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idDanhmuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tensp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tensp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinh)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.hinh)" height="200px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giaban)
        </dt>

        <dd>
            @String.Format("{0:N0}", Model.giaban)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaycapnhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaycapnhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluongton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluongton)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mota)
        </dt>

        <dd>
            @Html.Raw(Model.mota)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

shopquanao/shopquanao/Views/Admin/Details.cshtml
@model shopquanao.Models.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="col-lg-12 padding-8">

    <dl class="dl-horizontal" style="overflow: hidden;">
        <div class="menu_option-head2">Chi tiết sản phẩm</div>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.idDanhmuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idDanhmuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tensp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tensp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinh)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.hinh)" height="200px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giaban)
        </dt>

        <dd>
            @String.Format("{0:N0}", Model.giaban)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaycapnhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaycapnhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluongton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluongton)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mota)
        </dt>

        <dd>
            @Html.Raw(Model.mota)
        </dd>

    </dl>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.masp }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

shopquanao/shopquanao/Views/Admin/DoanhThu.cshtml
@model IEnumerable<shopquanao.Models.DonHang>
@{
    ViewBag.Title = "DoanhThu";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
@if (Session["Staff"] != null)
{
    <div class="p-3 text-danger">Bạn không có quyền truy cập trang web này!!!</div>
}
else
{
<div class="col-lg-12 padding-8">

    <h3>Tổng Doanh Thu Đạt Được</h3>

    <h2>@String.Format("{0:N0}", @ViewBag.TongDoanhThu) vnđ</h2>

    @using (Html.BeginForm("DoanhThuNgay", "Admin", FormMethod.Post))
    {
        <h3 class="mt-5">Doanh thu theo ngày</h3>
        <input type="date" name="NgayGiao" required />

        <input type="submit" value="Kiểm tra" />

    }

    @using (Html.BeginForm("DoanhThuThang", "Admin", FormMethod.Post))
    {
        <h3 class="mt-5">Doanh thu theo tháng</h3>
        <input type="date" name="NgayGiao" required />

        <input type="submit" value="Kiểm tra" />

    }



</div>
}

shopquanao/shopquanao/Views/Admin/DoanhThuNgay.cshtml
@model IEnumerable<shopquanao.Models.DonHang>
@{
    ViewBag.Title = "DoanhThuNgay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@if (Session["Staff"] != null)
{
    <div class="p-3 text-danger">Bạn không có quyền truy cập trang web này!!!</div>
}
else
{

    <div class="col-lg-12 padding-8 ViewPrint">
        <h3>Doanh thu theo Ngày @ViewBag.Ngay<span> Tháng @ViewBag.Thang</span> <span> Năm @ViewBag.Nam</span></h3>

        <h3>Tổng số lượng sản phẩm bán được trong ngày: @ViewBag.DoanhThuNgayCount</h3>

        <h2>Tổng doanh thu trong ngày: @String.Format("{0:N0}", @ViewBag.DoanhThuNgay) vnđ</h2>

        <div class="body fix-width scroll-inner">
            <table class="table table-striped">
                <tr>
                    <th>
                        mã kh
                    </th>
                    <th>
                        thanh toán
                    </th>
                    <th>
                        Trạng thái
                    </th>
                    <th>
                        Ngày đặt
                    </th>
                    <th>
                        Ngày giao
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in ViewBag.ListCountDTN)
                {
                    <tr>
                        <td>

                            @item.donhang.makh
                        </td>
                        <td>
                            @item.donhang.thanhtoan
                        </td>
                        <td>
                            <div style="color: green;">@item.donhang.giaohang</div>
                        </td>
                        <td>
                            @item.donhang.ngaydat
                        </td>
                        <td>
                            @item.donhang.ngaygiao
                        </td>

                        <td>
                            <a href="@Url.Action("DetailsCTDH", "QLDonHang", new { id = @item.donhang.madon })">Chi tiết đơn hàng</a> |
                            <a href="@Url.Action("Edit", "QLDonHang", new { id = @item.donhang.madon })">Sửa</a> |
                            <a href="@Url.Action("Delete", "QLDonHang", new { id = @item.donhang.madon })">Xóa</a>
                        </td>
                    </tr>

                }

            </table>
        </div>
    </div>


    <div class="body padding-8" style="border: none; box-shadow: none; border-radius: none; margin-top: 10px;">
        <div>
            <button id="Print" class="btn btn-primary">Print</button>
        </div>

        <div class="mt-2">
            @Html.ActionLink("Quay lại", "DoanhThu")
        </div>
    </div>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="~/Content/admin/js/printThis.js"></script>


    <script>
        jQuery(document).ready(function ($) {
            $('#Print').on("click", function () {
                $('.ViewPrint').printThis({
                    debug: false,               
                    importCSS: true,            
                    importStyle: false,         
                    printContainer: true,       
                    loadCSS: "",                
                    pageTitle: "",              
                    removeInline: false,        
                    removeInlineSelector: "*",  
                    printDelay: 333,            
                    header: null,               
                    footer: null,               
                    base: false,                
                    formValues: true,           
                    canvas: false,              
                    doctypeString: '...',       
                    removeScripts: false,       
                    copyTagClasses: false,      
                    beforePrintEvent: null,     
                    beforePrint: null,          
                    afterPrint: null            
                });
            });
        });
    </script>

}

shopquanao/shopquanao/Views/Admin/DoanhThuThang.cshtml
@model IEnumerable<shopquanao.Models.DonHang>
@{
    ViewBag.Title = "DoanhThuThang";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@if (Session["Staff"] != null)
{
    <div class="p-3 text-danger">Bạn không có quyền truy cập trang web này!!!</div>
}
else
{

    <div class="col-lg-12 padding-8 ViewPrint">
        <h3>Doanh thu theo tháng @ViewBag.Thang<span>Năm @ViewBag.Nam</span></h3>

        <h3>Tổng số lượng sản phẩm bán được trong tháng: @ViewBag.DoanhThuThangCount</h3>

        <h2>Tổng doanh thu trong tháng: @String.Format("{0:N0}", @ViewBag.DoanhThuThang) vnđ</h2>

        <div class="body fix-width scroll-inner">
            <table class="table table-striped">
                <tr>
                    <th>
                        mã kh
                    </th>
                    <th>
                        thanh toán
                    </th>
                    <th>
                        Trạng thái
                    </th>
                    <th>
                        Ngày đặt
                    </th>
                    <th>
                        Ngày giao
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in ViewBag.ListCountDTN)
                {
                    <tr>
                        <td>

                            @item.donhang.makh
                        </td>
                        <td>
                            @item.donhang.thanhtoan
                        </td>
                        <td>
                            <div style="color: green;">@item.donhang.giaohang</div>
                        </td>
                        <td>
                            @item.donhang.ngaydat
                        </td>
                        <td>
                            @item.donhang.ngaygiao
                        </td>

                        <td>
                            <a href="@Url.Action("DetailsCTDH", "QLDonHang", new { id = @item.donhang.madon })">Chi tiết đơn hàng</a> |
                            <a href="@Url.Action("Edit", "QLDonHang", new { id = @item.donhang.madon })">Sửa</a> |
                            <a href="@Url.Action("Delete", "QLDonHang", new { id = @item.donhang.madon })">Xóa</a>
                        </td>
                    </tr>

                }

            </table>
        </div>
    </div>

    <div class="body padding-8" style="border: none; box-shadow: none; border-radius: none; margin-top: 10px;">
        <div>
            <button id="Print" class="btn btn-primary">Print</button>
        </div>

        <div class="mt-2">
            @Html.ActionLink("Quay lại", "DoanhThu")
        </div>
    </div>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="~/Content/admin/js/printThis.js"></script>


    <script>
        jQuery(document).ready(function ($) {
            $('#Print').on("click", function () {
                $('.ViewPrint').printThis({
                    debug: false,               
                    importCSS: true,            
                    importStyle: false,         
                    printContainer: true,       
                    loadCSS: "",                
                    pageTitle: "",              
                    removeInline: false,        
                    removeInlineSelector: "*",  
                    printDelay: 333,            
                    header: null,               
                    footer: null,               
                    base: false,                
                    formValues: true,           
                    canvas: false,              
                    doctypeString: '...',       
                    removeScripts: false,       
                    copyTagClasses: false,      
                    beforePrintEvent: null,     
                    beforePrint: null,          
                    afterPrint: null            
                });
            });
        });
    </script>


}

shopquanao/shopquanao/Views/Admin/QLSanPham.cshtml
@model PagedList.IPagedList<shopquanao.Models.SanPham>
@using PagedList.Mvc;
@{
    ViewBag.Title = "QLSanPham";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-lg-12 padding-8">
    <div class="list">
        <div class="menu_option-head">Danh sách sản phẩm</div>
        <div class="add-product">
            <a href="@Url.Action("Create")">Thêm sản phẩm</a>
        </div>

        <table class="table">
            <thead>
            <th>Danh Muc</th>
            <th>tên sản phẩm</th>
            <th>hình</th>
            <th>giá</th>
            <th>ngày cập nhập</th>
            <th>số lượng tồn</th>
            <th>Chức năng</th>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.idDanhmuc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tensp)
                    </td>
                    <td>
                        <img src=" @Html.DisplayFor(modelItem => item.hinh)" height="100px" />
                    </td>
                    <td>
                        @String.Format("{0:N0}", item.giaban)
                    </td>
                    <td>
                        @item.ngaycapnhat
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.soluongton)
                    </td>
                    <td>
                        <a href="@Url.Action("Details", "Admin", new { id = item.masp })" class="btn btn-success"><i class="fa-solid fa-eye"></i></a>
                        <a href="@Url.Action("Edit", "Admin", new { id = item.masp })" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                        <a href="@Url.Action("Delete", "Admin", new { id = item.masp })" class="btn btn-danger"><i class="fa-solid fa-trash-can"></i></a>
                    </td>
                </tr>
            }


        </table>

    </div>

    <div class="d-flex justify-content-center">
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("QLSanPham", new
            {
                page = page
            }))
        </div>
    </div>

</div>