shopquanao/shopquanao/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using shopquanao.Models;
using System.Security.Cryptography;
using System.Text;
using shopquanao.Common;
using System.Net.Mail;
using System.Net;

namespace shopquanao.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        MyDataDataContext data = new MyDataDataContext();

        [HttpGet]
        public ActionResult DangKy()
        {
            return View();

        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["hoten"];
            var tendangnhap = collection["tendangnhap"];
            var matkhau1 = collection["matkhau"];
            var matkhau = Encryptor.MD5Hash(matkhau1);

            var MatKhauXacNhan1 = collection["MatKhauXacNhan"];
            var MatKhauXacNhan = Encryptor.MD5Hash(MatKhauXacNhan1);

            var email = collection["email"];
            var diachi = collection["diachi"];
            var dienthoai = collection["dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["ngaysinh"]);
            if (matkhau1.Length < 8)
            {
                ViewData["Length>8"] = "Mật khẩu phải dài hơn 7 kí tự";
            }

            else if (String.IsNullOrEmpty(MatKhauXacNhan))
            {
                ViewData["NhapMKXN"] = "Phai nhap mat khau xac nhan";
            }
            
            else
            {
                if (!matkhau.Equals(MatKhauXacNhan))
                {
                    ViewData["MatKhauGiongNhau"] = "Mat khau va mat khau xac nhan phai giong nhau";
                }

                else
                {
                    kh.hoten = hoten;
                    kh.tendangnhap = tendangnhap;
                    kh.matkhau = matkhau;
                    kh.email = email;
                    kh.diachi = diachi;
                    kh.dienthoai = dienthoai;
                    kh.ngaysinh = DateTime.Parse(ngaysinh);

                    data.KhachHangs.InsertOnSubmit(kh);
                    data.SubmitChanges();

                    return RedirectToAction("DangNhap");
                }
            }
            return this.DangKy();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();

        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendangnhap = collection["tendangnhap"];
            var matkhau1 = collection["matkhau"];

            var matkhau = Encryptor.EncryptMD5(matkhau1);

            KhachHang kh =
                data.KhachHangs.FirstOrDefault(n => n.tendangnhap == tendangnhap && n.matkhau == matkhau);

            if (kh != null)
            {

                Session["TaiKhoan"] = kh;
                Session["Username"] = tendangnhap;


                if (kh.RoleID == 1)
                {
                    Session["Admin"] = kh;
                    return RedirectToAction("Index", "Admin");
                }
                else if (kh.RoleID == 3)
                {
                    Session["Staff"] = kh;
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    return RedirectToAction("ListSanPham", "SanPham");
                }

            }
            else
            {
                ViewBag.msg = "Tên đăng nhập hoặc mật khẩu không chính xác";
                return View();
            }

        }

        public ActionResult DangXuat()
        {
            FormsAuthentication.SignOut();
            Session.Abandon(); // it will clear the session at the end of request
            Session.Clear();
            return RedirectToAction("ListSanPham", "SanPham");
        }


        [NonAction]
        public void SendVerificationLinkEmail(string emailID, string activationCode, string emailFor = "VerifyAccount")
        {
            var verifyUrl = "/NguoiDung/" + emailFor + "/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress("langtuankiet883@gmail.com", "ShopQuanAo");
            var toEmail = new MailAddress(emailID);
            var fromEmailPassword = "01694512357"; 
            
            string subject = "";
            string body = "";
            if (emailFor == "VerifyAccount")
            {
                subject = "Tai khoan da duoc tao thanh cong";
                body = "chua lam";
            }
            else if (emailFor == "ResetPassword")
            {
                subject = "Reset password";
                body = "Bạn vừa gửi link xác thực tài khoản, Hãy click vào link bên dưới để lấy lại mật khẩu<br>" +
                    "<a href=" + link + ">Reset password</a>";
            }

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)

            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
            {
                smtp.EnableSsl = true;
                smtp.Send(message);
            }    

            

            
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(string EmailID)
        {
            string message = "";
            MyDataDataContext data = new MyDataDataContext();
            var account = data.KhachHangs.Where(a => a.email == EmailID).FirstOrDefault();
            if (account != null)
            {
                string resetCode = Guid.NewGuid().ToString();
                SendVerificationLinkEmail(account.email, resetCode, "ResetPassword");
                account.resetpasswordcode = resetCode;

                data.SubmitChanges();

                message = "Một đường link đã được gửi đến email của bạn";
            }
            else
            {
                message = "Email không tồn tại";
            }
            ViewBag.Message = message;
            return View();
        }

        public ActionResult ResetPassword(string id)
        {
            MyDataDataContext data = new MyDataDataContext();
            var user = data.KhachHangs.Where(a => a.resetpasswordcode == id).FirstOrDefault();
            if (user != null)
            {
                ResetPasswordModel model = new ResetPasswordModel();
                model.ResetCode = id;
                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResetPassword(ResetPasswordModel model)
        {
            var message = "";
            if (ModelState.IsValid)
            {
                MyDataDataContext data = new MyDataDataContext();
                var user = data.KhachHangs.Where(a => a.resetpasswordcode == model.ResetCode).FirstOrDefault();
                if (user != null)
                {
                    user.matkhau = Encryptor.MD5Hash(model.NewPassword);
                    user.resetpasswordcode = "";

                    data.SubmitChanges();
                    message = "Cập nhập mật khẩu thành công";
                }
            }
            else
            {
                message = "Cập nhập mật khẩu thất bại";
            }
            ViewBag.Message = message;
            return View(model);
        }
    }
}

shopquanao/shopquanao/Controllers/XemDonHangController.cs
using shopquanao.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shopquanao.Controllers
{
    public class XemDonHangController : Controller
    {
        // GET: XemDonHang
        MyDataDataContext data = new MyDataDataContext();
        // GET: DanhMuc
        //---------Index-DanhMuc------------
        public ActionResult Index()
        {
            var all_danhmuc = from dh in data.DonHangs
                              join kh in data.KhachHangs on dh.makh equals kh.makh
                              where kh.tendangnhap == Session["Username"]
            select dh;

            return View(all_danhmuc);

        }

        //---------Detail-------------
        public ActionResult DetailsCTDH2(int id)
        {
            var results = (from t1 in data.ChiTietDonHangs
                           join t2 in data.DonHangs
                           on new { t1.madon } equals
                               new { t2.madon }
                           where t2.madon == id
                           select t1).ToList();
            List<SanPham> sanpham = data.SanPhams.ToList();
            List<ChiTietDonHang> ctdh = data.ChiTietDonHangs.ToList();
            List<KhachHang> khachhang = data.KhachHangs.ToList();
            List<DonHang> donhang = data.DonHangs.ToList();
            var ViewKH2 = from kh in khachhang join dh in donhang
                         on kh.makh equals dh.makh
                         where dh.madon == id && kh.makh == dh.makh
                         select new ViewModel
                         {
                             khachhang = kh,
                             donhang = dh
                         };
            var ViewSP = from sp in sanpham
                         join ct in ctdh
      on sp.masp equals ct.masp
                         where ct.madon == id && sp.masp == ct.masp
                         select new ViewModel
                         {
                             sanpham = sp,
                             ctdh = ct
                         };

            ViewBag.ViewSP = ViewSP;

            ViewBag.ViewChiTietDH2 = ViewKH2;
            return View(results);
        }

    }
}

shopquanao/shopquanao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Quần Áo</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/css/style.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
    <link href="~/Content/css/tooplate-main.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
            <!----<a class="navbar-brand" href="#"><img src="~/Content/images/logo.png" alt=""></a>-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <style>
                #navbarResponsive {
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    z-index: unset;
                    position: unset;
                    left: unset;
                    top: unset;
                    transform: unset;
                }
            </style>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav d-flex justify-content-between" style="width: 100%;">
                    <div style="margin-right: auto;" class="d-flex">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">
                            TRANG CHỦ
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("TatCaSanPham", "SanPham")">SẢN PHẨM</a>
                    </li>

                    @if (Session["TaiKhoan"] != null)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "XemDonHang")">ĐƠN HÀNG</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <div class="nav-link" style="opacity:0.5;" disabled>ĐƠN HÀNG</div>
                        </li>
                    }


                    <li class="nav-item">
                        <div class="nav-link">
                            @using (Html.BeginForm("TimKiem", "TimKiem", FormMethod.Get, new { @class = "navbar__search" }))
                            {
                                @Html.TextBox("search", null, new { @class = "search form-label", placeholder = "Nhập để tìm kiếm", required = "required" })
                            }
                        </div>

                    </li>
</div>

                    <div class="d-flex">
                    <li class="nav-item">
                        @Html.Action("GioHangPartial", "GioHang", new { @class = "giohang" })
                    </li>
                    <li class="nav-item">
                        @if (Session["TaiKhoan"] != null)
                        {
                        <li class="nav-link custom-user">
                            @Session["Username"].ToString()

                        </li>
                        <a href="@Url.Action("DangXuat", "NguoiDung")" class="nav-link custom-user">
                            <span class="fas fa-sign-out-alt"></span>
                        </a>
                    }
                    else
                    {
                        <div class="login">
                            <a href="@Url.Action("DangNhap", "NguoiDung")" class="nav-link">
                        <li class="nav-item">Đăng nhập</li></a>
                </div>
            }
                        </li>

                    </div>
                      

                        </ul>
                    </div>
                    </div>
                </nav>


                @RenderBody()
                <hr />
                <div class="subscribe-form">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="section-heading">
                                    <div class="line-dec"></div>
                                    <h1>Nhập email của bạn để liên hệ chúng tôi !</h1>
                                </div>
                            </div>
                            <div class="col-md-8 offset-md-2">
                                <div class="main-content">

                                    <div class="container">
                                        <form id="subscribe" action="" method="get">
                                            <div class="row">
                                                <div class="col-md-7">
                                                    <fieldset>
                                                        <input name="email" type="text" class="form-control" id="email" onfocus="if(this.value == 'Your Email...') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Your Email...';}" value="Your Email..." required="">
                                                    </fieldset>
                                                </div>
                                                <div class="col-md-5">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="button">LIÊN HỆ NGAY!</button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sub-footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright-text">
                                    <p>
                                        Copyright &copy; 2022 by  Nguyen Thanh Tin


                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!---<div class="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="logo">
                                    <img src="assets/images/header-logo.png" alt="">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="footer-menu">
                                    <ul>
                                        <li><a href="#">Home</a></li>
                                        <li><a href="#">Help</a></li>
                                        <li><a href="#">Privacy Policy</a></li>
                                        <li><a href="#">How It Works ?</a></li>
                                        <li><a href="#">Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="social-icons">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="go-to-top"><i class="fas fa-chevron-up"></i></div>-->


                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/bootstrap")
                <script src="~/Content/scripts/ckfinder/ckfinder.js"></script>
                <script src="~/Content/scripts/ckeditor/ckeditor.js"></script>
                @RenderSection("upload", required: false)
                @RenderSection("scripts", required: false)

                <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
                <script>
                    //Slider using Slick
                    $(document).ready(function () {
                        $('.post-wrapper').slick({
                            slidesToScroll: 1,
                            autoplay: true,
                            arrow: true,
                            dots: true,
                            autoplaySpeed: 5000,
                            prevArrow: $('.prev'),
                            nextArrow: $('.next'),
                            appendDots: $(".dot"),
                        });
                    });
                </script>

                <!-- Additional Scripts -->
                <script src="~/Content/scripts/custom.js"></script>

                <script language="text/Javascript">
                    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
                    function clearField(t) {                   //declaring the array outside of the
                        if (!cleared[t.id]) {                      // function makes it static and global
                            cleared[t.id] = 1;  // you could use true and false, but that's more typing
                            t.value = '';         // with more chance of typos
                            t.style.color = '#fff';
                        }
                    }
                </script>

                <script src="~/Content/scripts/script.js"></script>
            </body>
</html>